void main(){
  ElementDescription elementDescription = ElementDescription();

  print("${elementDescription.getElementDescription(2)}");
}

class ElementDescription{

 String getElementDescription(int elementNumber){
    return elementDescription[elementNumber + 1];
  }

  List elementDescription = [

    /* 0   */  ' No NEED TO SPECIFY ' ,
    /* 1   */  'Next time you find out you gained a "little" extra kilos over Christmas, you could blame this element partly for that. About 10 percent of the weight of living organisms is hydrogen – mainly in water, proteins and fats. And you all know how much fats we gain over the holidays.  ' ,
    /* 2   */  'Balloons seem to have a thing with the Sun. It flies towards the sun, is as dangerous as it (VERY VERY dangerous for your eardrums) and even LOOKS like it. Maybe it is because element 2 likes it too. (Geddit?) Helium was discovered in the Sun’s atmosphere before it was found on Earth. They both make a very weird couple.  ' ,
    /* 3   */  'Some people look tough but aren"t. Lithium is sadly one of them. Although it is a metal, it is soft enough to cut with a knife.  ' ,
    /* 4   */  'Although it may not be as well-known as oxygen or hydrogen, Beryllium has a long history, having been known to the ancient Egyptians in beryl and in emeralds.  ' ,
    /* 5   */  'Looks like we"re not the only animals with skin problems. Snake often have skin issues that require some cure. Borax is a widely used Boron compound that is used to give slimy serpents some relief from skin issues.  ' ,
    /* 6   */  'Carbon is such an all-rounder, it can"t make up its mind on what it wants to be. Elemental carbon can take the form of one of the hardest substances (diamond) or one of the softest (graphite).' ,
    /* 7   */  'Chemistry is usually not funny, but Nitrogen will keep you laughing all day! Nitrogen is used as laughing gas at the dentist, to distract your mind from the painful dental procedures and help you relax! At least it’s better than my father’s jokes... ' ,
    /* 8   */  'Nature’s Chosen One loves colors. Solid and liquid oxygen usually appear light blue, but it can also appear in red, orange, pink, and black! ' ,
    /* 9   */  'This highly explosive element is carbon s arch-nemesis. Fluorine is one of the few elements that can attack diamond. Anybody want to watch Carbonman Vs. Fluorineman? ' ,
    /* 10   */  'News flash: Neon, the New Helium? If you always find your helium balloons keep flying away from you, you may want to consider gaseous neon as your new balloon guy. If you fill a balloon with neon, it will rise in the air, but it would do it at a much slower rate than a helium-filled one. The balloon-stealing sky wouldnot be happy though... ' ,
    /* 11   */  'Sir Humphry Davy was a chemistry genius for a reason. It takes most chemists years (or decades) to find a new element. After discovering potassium, he discovered sodium within a few days. Talk about smart! ' ,
    /* 12   */  'Like carbons diamond, magnesium is almost invincible. What would you do if you saw a magnesium fire? Spray nitrogen or carbon dioxide? Won"t work! Pour water to put it out? That will only make it worse! Magnesium fires are hard to put out, because they can burn through nitrogen carbon dioxide and water.  ' ,
    /* 13   */  'Ever wonder why you don"t see the thirteenth element in biology? Because of the number 13"s bad luck! Aluminium has no function in biology.  ' ,
    /* 14   */  'Diamond has a side-kick, and it"s called Silicon Carbide(SiC). SiC is nearly as hard as diamond.  ' ,
    /* 15   */  'Ah, phosphorus, the element that makes chemistry feel like the hardest spelling test ever. There are two super-villains called White Phosphorus and Black Phosphorus. White phosphorus is the "destroy everything '
                 'within reach" type that can cause severe burns if you touch it. Black Phosphorus is the "evil impostor" type that looks like graphite powder and conducts electricity even though it is not a metal. Watch out for the Colorful Phosphorus Brothers!  ' ,
    /* 16   */  'Sulfur is taking over the moon! Or rather, one of Jupiter"s moons, Io. It appears yellow due to the large amount of sulfur on its surface. This sulfur comes from its many active volcanoes.  ' ,
    /* 17   */  'Ugh. The smelly stuff in the swimming pool. Apparently it"s deadly too! Chlorine gas was used by the Germans in World War I to poison Allied soldiers.  ' ,
    /* 18   */  'Amazingly, argon is a lot like humans. It"s a homework slacker, chill-out guy and couch potato who ain"t care about nothing. Literally. The name argon comes from the Greek word "argos" meaning "lazy" or "inactive." (It"s also best friends with aluminium, because it has nothing to do with biology too!)  ' ,
    /* 19   */  'Where do you think we can find potassium in our food? Potatoes ? (Because it"s called "potassium")Correct! It can also be found in bananas, avocados, nuts, parsley, and chocolate. (Mmm...)  ' ,
    /* 20   */  'Calcium and lime are soulmates. Calcium is named after the Greek name for lime, "calx", which is calcium oxide.  ' ,



    /* 21   */  'Looks like you"re not the only one who failed in Geography! Although scandium was discovered by a Swedish chemist who named it after his homeland Scandinavia (Sweden is part of Scandinavia), it is usually found in Norway (home of the vikings that is another part of Scandinavia), and Madagascar (all the way in Africa!). Say hi to the lemurs for me, Scann!  ' ,
    /* 22   */  'Like scandium, titanium is another globe-trotter. Or rather, outer-space-trotter! Titanium is found in meteorites, on the Moon, and in some types of stars, but it is also found in the Earth"s crust (though not as a pure element. It is used to make anything from high-end golf clubs and tennis rackets to plated towns at a museum in Spain.  ' ,
    /* 23   */  'Always complaining that the names of elements are way to complicated? Well, it could have been a lot worse! Vanadium wasn"t originally supposed to be called vanadium. Proposed names for Element 23 included rionium, panchromium and erythronium. Personally, I"m relieved that vanadium is easier to spell  ' ,
    /* 24   */  'Roses are red, while violets are blue. Rubies are red, while chronium is black/gray/blue/violet/orange/green/yellow/purple/other colors/red too! In fact, rubies get their red color from small traces of chromium!  ' ,
    /* 25   */  'In the periodic table, we have friends like H2O (water), and enemies like mercury or lead. However, manganese (no, it"s not the language of manga!) is considered a frenemy-- although we need it to survive, such as for liver and kidney functioning, our bodies cannot store it!  ' ,
    /* 26   */  'It is common knowledge not to eat things like iron bolts or screws. However, do you know that you"re actually eating it almost every day-- even without you knowing? Food sources of iron, which is good for your body, include red meat, beans, fish, and green leafy vegetables. (Note: these food sources DO NOT include the iron magnets in your science lab!)  ' ,
    /* 27   */  'Hey, fantasy lovers! If you hate chemistry (which probably everybody does except for me), then this fact is for you! The name cobalt comes from the German word kobold, meaning "goblin ore." How magical!  ' ,
    /* 28   */  'Warning: Bombshell ahead! Why are nickel and copper mortal enemies? Here"s the exclusive scoop! Although the U.S. five cent coin is called the "nickel", it is actually three-quarters made of copper! Only 25% of it is made by nickel, so nickel had stolen the credit and technically it should be called the "copper"! That scoundrel!  ' ,
    /* 29   */  'Pure gold is so soft that you can shape it with your hands, which is why most gold jewellery is actually a mixture of gold, silver and copper. In Europe, it was forbidden to alloy gold with metals other than silver and copper up until the 19th century. Even twenty-four carat gold contains copper!  ' ,
    /* 30   */  'Zinc is found everywhere in daily life: in every cell of the human body, in the earth, in the food we eat and in products we use (sunblock, automobiles, cosmetics, airplanes, appliances, surgical tools, zinc lozenges).  ' ,
    /* 31   */  'Liquid gallium cannot be kept in a glass or metal container because it expands 3.1 percent when it freezes. and Gallium has been used in nuclear bombs to stabilize the crystal structure  ' ,
    /* 32   */  'Germanium is metalloid, which means it has properties of both metals and nonmetals. Other metalloids on the periodic table are boron, silicon, arsenic, antimony, tellurium, and polonium, according to the Los Alamos National Laboratory.  ' ,
    /* 33   */  'As early as 82 B.C., the Roman dictator Lucius Cornelius Sulla attempted to end a rash of arsenic poisonings by passing the Lex Cornelia, the first known law against poisoning, according to Dartmouth College.  ' ,
    /* 34   */  'Selenium gets its name from the Greek word "selene," which means "moon." Selene was the Greek goddess of the moon and Selenium is protective against mercury poisoning.  ' ,
    /* 35   */  'Bromine is a halogen, according to Chemicool. Halogen elements (fluorine, chlorine, bromine, iodine and astatine) are never found alone in nature and produce salts when reacting with metals.  ' ,
    /* 36   */  'OK, let"s talk Superman. The superhero"s home world was first referenced in 1938. At first, the Superman comics referenced all residents of the destroyed planet of Krypton as possessing super strength; by the 1950s, however, the story shifted. Superman would have been an average Joe on Krypton, but Earth"s lighter gravity and yellow sun gave him his superpowers.  ' ,
    /* 37   */  'Rubidium is a silvery-white and very soft metal — and one of the most highly reactive elements on the periodic table. Rubidium has a density about one and a half times that of water and is solid at room temperature, although the metal will melt if it"s just a bit warmer, according to Chemicool.   ' ,
    /* 38   */  'The first large-scale application of strontium was in the beet sugar industry just prior to World War I. More than 100,000 tons of strontium hydroxide were used each year in the sugar crystallization process.  ' ,
    /* 39   */  'Yttrium (Y) has an atomic number of thirty-nine. This rare-earth element ignites easily in air, and has been found in rocks retrieved from the moon.  ' ,
    /* 40   */  'Zirconium doesn’t just exist here on Earth. Scientists also believe that there is some level of zirconium on the sun. Additionally, NASA has found zirconium in some of the lunar rock obtained from the moon. And there is also likely zirconium in many meteorites floating through the solar system.  ' ,
    /* 41   */  'Niobium is named for the Greek goddess of tears, Niobe, who was the daughter of king Tantalus, according to the Royal Society of Chemistry, due to the element"s similarities to tantalum (named for the king).  ' ,
    /* 42   */  '"Big Bertha," the German 43-ton gun used in World War II, contained molybdenum, rather than iron, as an essential component of its steel, because of its much higher melting point.  ' ,
    /* 43   */  'Technetium is the only element that is artificially produced. This property gives technetium its name, from the Greek for "artificial."  ' ,
    /* 44   */  'The element name comes from the Latin word ‘Ruthenia’. Ruthenia means Russia, which refers to the Ural Mountains of Russia, the original source of the platinum metal group ores  ' ,
    /* 45   */  'South African PGM producers extract a mix of metals comprising approximately 60 percent platinum, 30 percent palladium and 10 percent rhodium,   ' ,
    /* 46   */  'Palladium"s most incredible ability is that it can absorb up to 900 times its volume of hydrogen, according to the Thomas Jefferson National Accelerator Facility. Because of this ability, palladium is used to store and filter hydrogen.  ' ,
    /* 47   */  'Silver is super shiny! Polished silver reflects 95% of the visible light spectrum, which makes it the most reflective metal. Because of that, many mirrors are coated with it. Its reflective properties are also used for objects like telescopes, microscopes and solar panels  ' ,
    /* 48   */  'Cadmium makes up 150 parts per billion by weight in the crust of the Earth and is typically found with zinc, which has very similar chemical properties, according to Chemicool.   ' ,
    /* 49   */  'Indium metal gives off a high-pitched "scream," when bent. Similar to the "tin cry," this scream sounds more like a crackling sound.  ' ,
    /* 50   */  'When tin is bent at room temperature, it makes a high-pitched creaking sound known as the "tin cry," caused by the deformation of tin crystals  ' ,
    /* 51   */  'China is typically the top global producer of antimony, extracting between 84% and 88% of the supply. Antimony is ranked first on the British Geological Survey"s Risk List, due to its supply.  ' ,
    /* 52   */  'Tellurium is one of the rarest elements on Earth, but is abundant in space. It is found on Earth with nearly the same abundance as platinum.  ' ,
    /* 53   */  'We get most of our iodine from milk. Iodine regulates our metabolism. It was used to make the first photographs  ' ,
    /* 54   */  '  ' ,
    /* 55   */  '  ' ,
    /* 56   */  '  ' ,
    /* 57   */  '  ' ,
    /* 58   */  '  ' ,
    /* 59   */  '  ' ,
    /* 60   */  '  ' ,
    /* 61   */  '  ' ,
    /* 62   */  '  ' ,
    /* 63   */  '  ' ,
    /* 64   */  '  ' ,
    /* 65   */  '  ' ,
    /* 66   */  '  ' ,
    /* 67   */  '  ' ,
    /* 68   */  '  ' ,
    /* 69   */  '  ' ,
    /* 70   */  '  ' ,
    /* 71   */  '  ' ,
    /* 72   */  '  ' ,
    /* 73   */  '  ' ,
    /* 74   */  '  ' ,
    /* 75   */  '  ' ,
    /* 76   */  '  ' ,
    /* 77   */  '  ' ,
    /* 78   */  '  ' ,
    /* 79   */  '  ' ,
    /* 80   */  '  ' ,
    /* 81   */  '  ' ,
    /* 82   */  '  ' ,
    /* 83   */  '  ' ,
    /* 84   */  '  ' ,
    /* 85   */  '  ' ,
    /* 86   */  '  ' ,
    /* 87   */  '  ' ,
    /* 88   */  '  ' ,
    /* 89   */  '  ' ,
    /* 90   */  '  ' ,
    /* 91   */  '  ' ,
    /* 92   */  '  ' ,
    /* 93   */  '  ' ,
    /* 94   */  '  ' ,
    /* 95   */  '  ' ,
    /* 96   */  '  ' ,
    /* 97   */  '  ' ,
    /* 98   */  '  ' ,
    /* 99   */  '  ' ,
    /* 100   */  '  ' ,
    /* 101   */  '  ' ,
    /* 102   */  '  ' ,
    /* 103   */  '  ' ,
    /* 104   */  '  ' ,
    /* 105   */  '  ' ,
    /* 106   */  '  ' ,
    /* 107   */  '  ' ,
    /* 108   */  '  ' ,
    /* 109   */  '  ' ,
    /* 110   */  '  ' ,
    /* 111   */  '  ' ,
    /* 112   */  '  ' ,
    /* 113   */  '  ' ,
    /* 114   */  '  ' ,
    /* 115   */  '  ' ,
    /* 116   */  '  ' ,
    /* 117   */  '  ' ,
    /* 118   */  '  ' ,
    /* 119   */  '  ' ,

  ];

}